---

- name: Ensure required packages for EJBCA installation are present.
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - ant.noarch

- name: Ensure database for EJBCA is present.
  mysql_db:
    name: ejbca
    state: present

- name: Ensure MariaDB user for EJBCA is present.
  mysql_user:
    name: ejbca
    password: ejbca
    priv: "*.*:ALL,GRANT"
    state: present

- name: Download JBOSS AS archive.
  get_url:
    url: "http://download.jboss.org/jbossas/{{ jboss_version.split('.')[0] }}.{{ jboss_version.split('.')[1] }}/jboss-as-{{ jboss_version }}.Final/jboss-as-{{ jboss_version }}.Final.zip"
    dest: /opt/

- name: Download EJBCA archive.
  get_url:
    url: "http://sourceforge.net/projects/ejbca/files/ejbca6/ejbca_{{ ejbca_version | regex_replace('.','_') }}/ejbca_ce_{{ ejbca_version | regex_replace('.','_') }}.zip"
    dest: /opt/

- name: Add JBOSS system user.
  user:
    name: jboss
    system: True

- name: Unarchive JBOSS archive.
  unarchive:
    src: "/opt/jboss-as-{{ jboss_version }}.Final.zip"
    dest: /opt/
    owner: jboss
    group: jboss
    creates: "/opt/jboss-as-{{ jboss_version }}.Final"

- name: Unarchive EJBCA archive.
  unarchive:
    src: "/opt/ejbca_ce_{{ ejbca_version | regex_replace('.','_') }}.zip"
    dest: /opt/
    owner: jboss
    group: jboss
    creates: "/opt/ejbca_ce_{{ ejbca_version | regex_replace('.','_') }}"

- name: Create symlink for /opt/jboss
  file:
    src: "/opt/jboss-as-{{ jboss_version }}.Final"
    dest: /opt/jboss
    state: link
    owner: jboss
    group: jboss

- name: Create symlink for /opt/ejbca
  file:
    src: "/opt/ejbca_ce_{{ ejbca_version | regex_replace('.','_') }}"
    dest: /opt/ejbca
    state: link
    owner: jboss
    group: jboss

- name: Configure install.properties.
  template:
    src: install.properties.j2
    dest: /opt/ejbca/conf/install.properties

- name: Configure ejbca.properties.
  template:
    src: ejbca.properties.j2
    dest: /opt/ejbca/conf/ejbca.properties

- name: Configure database.properties.
  template:
    src: database.properties.j2
    dest: /opt/ejbca/conf/database.properties

- name: Configure web properties.
  template:
    src: web.properties.j2
    dest: /opt/ejbca/conf/web.properties

- name: Ensure MariaDB Java Connector directory is present.
  file:
    path: /opt/jboss/modules/org/mariadb/main/
    state: directory
    recurse: True

- stat:
    path: "/opt/jboss/modules/org/mariadb/main/mariadb-java-client-{{ mariadb_java_client_version }}.jar"
  register: mariadb_connector

- name: Download MariaDB Java Connector.
  get_url:
    url: "https://downloads.mariadb.com/enterprise/hvnn-wb2d/connectors/java/connector-java-1.3.2/mariadb-java-client-{{mariadb_java_client_version }}.jar"
    dest: /opt/jboss/modules/org/mariadb/main/
    validate_certs: False
    owner: jboss
    group: jboss
  when: mariadb_connector.stat is not defined

- name: Ensure MariaDB Java Connector configuration is present.
  template:
    src: modules.xml.j2
    dest: /opt/jboss/modules/org/mariadb/main/modules.xml
    owner: jboss
    group: jboss

- name: Ensure MariaDb connector is configured in JBOSS.
  template:
    src: standalone.xml.j2
    dest: /opt/jboss/standalone/configuration/standalone.xml

- name: Ensure JBOSS root directory is present.
  file:
    path: /etc/jboss-as
    state: directory

- name: Ensure JBOSS main configuration is present.
  template:
    src: jboss-as.conf.j2
    dest: /etc/jboss-as/jboss-as.conf

- name: Ensure JBOSS log directory is present.
  file:
    path: /var/log/jboss
    state: directory
    owner: jboss
    group: jboss

- name: Ensure JBOSS unit file is present.
  template:
    src: jboss.service.j2
    dest: /etc/systemd/system/jboss.service
  register: jboss_unit

- name: Reload systemd.
  systemd:
    name: jboss
    daemon_reload: True
  when: jboss_unit.changed

- name: Set permissions for JBOSS directory.
  file:
    path:  /opt/jboss
    state: directory
    owner: jboss
    group: jboss
    follow: True

- name: Start and enable JBOSS application server.
  service:
    name: jboss
    state: started
    enabled: True

- wait_for:
    port: 9999
    delay: 1

- name: Register MariaDB Java Connector.
  command: /opt/jboss/bin/jboss-cli.sh -c /subsystem=datasources/jdbc-driver=org.mariadb.jdbc.Driver:add\(driver-name=org.mariadb.jdbc.Driver,driver-module-name=org.mariadb,driver-xa-datasource-class-name=org.mariadb.jdbc.MySQLDataSource\)

- name: EJBCA ant deploy.
  command: ant deploy
  args:
    chdir: /opt/ejbca

- name: EJBCA ant install.
  command: ant install
  args:
    chdir: /opt/ejbca
